export const SYSTEM_COLLECTIONS = [
  {
    id: 'relationships',
    name: 'Relationships',
    color: 'bg-red-500',
    type: 'system',
  },
  {
    id: 'parenting',
    name: 'Parenting',
    color: 'bg-blue-500',
    type: 'system',
  },
  {
    id: 'finances',
    name: 'Finances',
    color: 'bg-green-500',
    type: 'system',
  },
  {
    id: 'work',
    name: 'Work',
    color: 'bg-yellow-500',
    type: 'system',
  },
  {
    id: 'education',
    name: 'Education',
    color: 'bg-purple-500',
    type: 'system',
  },
  {
    id: 'health-wellness',
    name: 'Health & Wellness',
    color: 'bg-pink-500',
    type: 'system',
  },
  {
    id: 'creativity',
    name: 'Creativity',
    color: 'bg-indigo-500',
    type: 'system',
  },
  {
    id: 'personal-growth',
    name: 'Personal Growth',
    color: 'bg-teal-500',
    type: 'system',
  },
  {
    id: 'faith',
    name: 'Faith',
    color: 'bg-gray-500',
    type: 'system',
  },
  {
    id: 'death',
    name: 'Death & Grief',
    color: 'bg-blue-400',
    type: 'system',
  },
  {
    id: 'travel-adventure',
    name: 'Travel & Adventure',
    color: 'bg-orange-500',
    type: 'system',
  },
  {
    id: 'family',
    name: 'Family',
    color: 'bg-amber-500',
    type: 'system',
  },
  {
    id: 'home-living',
    name: 'Home & Living',
    color: 'bg-lime-500',
    type: 'system',
  },
  {
    id: 'community',
    name: 'Community',
    color: 'bg-emerald-500',
    type: 'system',
  },
  {
    id: 'food',
    name: 'Food',
    color: 'bg-rose-500',
    type: 'system',
  },
  {
    id: 'nature',
    name: 'Nature',
    color: 'bg-green-400',
    type: 'system',
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    color: 'bg-violet-500',
    type: 'system',
  },
  {
    id: 'memories',
    name: 'Memories',
    color: 'bg-cyan-500',
    type: 'system',
  },
  {
    id: 'culture',
    name: 'Culture',
    color: 'bg-fuchsia-500',
    type: 'system',
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    color: 'bg-sky-500',
    type: 'system',
  },
  {
    id: 'events-celebrations',
    name: 'Events & Celebrations',
    color: 'bg-pink-400',
    type: 'system',
  },
  {
    id: 'self-care',
    name: 'Self-Care',
    color: 'bg-purple-400',
    type: 'system',
  },
  {
    id: 'productivity',
    name: 'Productivity',
    color: 'bg-yellow-400',
    type: 'system',
  },
  {
    id: 'fitness-sports',
    name: 'Fitness & Sports',
    color: 'bg-red-400',
    type: 'system',
  },
  {
    id: 'heritage',
    name: 'Heritage',
    color: 'bg-amber-400',
    type: 'system',
  },
  {
    id: 'technology',
    name: 'Technology',
    color: 'bg-indigo-400',
    type: 'system',
  },
  {
    id: 'life-lessons',
    name: 'Life Lessons',
    color: 'bg-teal-400',
    type: 'system',
  },
];
